# Use a imagem base do Python
FROM python:3.9-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo do Broker para o diretório de trabalho
COPY banco_a.py .
COPY banco.py .
COPY contaBancaria.py .
COPY contaConjunta.py .
COPY contaFisica.py .
COPY contaPJ.py .

# Instale o Flask
RUN pip install flask
RUN pip install requests

# Comando para iniciar o Broker
CMD ["python", "banco_a.py"]